title: "Cameron Movassaghi"
description: "Research, publications, and technical projects"
url: "https://csmova.github.io"
baseurl: ""  # Leave empty for user.github.io sites

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "air"  # Try "dark", "contrast", or "default" later
plugins:
  - jekyll-include-cache

# Author info
author:
  name: "Cameron Movassaghi"
  avatar: "/assets/images/avatar.png"  # Optional — add your headshot
  bio: "Post-doctoral Scientist | Computational Biomedicine @ Cedars-Sinai"
  location: "Los Angeles, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/csmova"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/csmova/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:csmova.gmail.com"

# Navigation
header_pages:
  - about.md
  - projects.md
  - publications.md
  - contact.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM
